name: Docs CI/CD

on:
  pull_request:
    branches: [develop]
  push:
    branches: [develop]

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: pip install mkdocs mkdocs-material

    - name: Build documentation
      run: mkdocs build

  deploy:
    needs: build-test
    if: github.event_name == 'push' && github.ref == 'refs/heads/develop'
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pages: write
      id-token: write
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: pip install mkdocs mkdocs-material

    - name: Deploy to GitHub Pages
      run: mkdocs gh-deploy --force --clean